version: '3'

services:
  dynadot-checker:
    build: .
    volumes:
      - ./config.js:/app/config.js
      - ./domain-price-history.json:/app/domain-price-history.json
    restart: "no" # Set to "no" for manual/cron execution 